import Head from "next/head";
import { Inter } from "next/font/google";
import { useState, useEffect } from "react";
import Header from "@/components/Header";
import AccessPage from "@/components/AccessPage";
import AccessModal from "@/components/AccessModal";
import Chat from "@/components/Chat";
import DynamicUtilityComponent from "@/components/DynamicUtility";
import { useAddress } from "@thirdweb-dev/react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const address = useAddress();
  const [showAccessModal, setShowAccessModal] = useState<boolean>(false);
  const [hasAccess, setHasAccess] = useState<boolean>(false);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={`w-screen min-h-screen relative flex flex-col bg-background ${inter.className}`}
      >
        <Header />
        {!hasAccess ? (
          <>
            <DynamicUtilityComponent />
            {/* {showAccessModal && (
              <DynamicUtilityComponent
                setShowAccessModal={setShowAccessModal}
                setHasAccess={setHasAccess}
              />
            )}
            ) */}
          </>
        ) : (
          <Chat />
        )}
      </main>
    </>
  );
}
